#!/bin/bash

#for debugging
#set -ex

#
# Copyright © 2023 Task Re-engineering Inc.
# All rights reserved.
# 
# This source code is licensed under the [] license found in the
# LICENSE file in the root directory of this source tree. 
#

## Usage: gitserverlite <command> [<arguments>]
##
## Commands:
##   add-branch <branch name>       Adds as branch to automatic deployment
##   remove-branch <branch name>    Removes a branch from automatic deployment
##   list                           Lists all branches that will automatically deploy
##   show-branch <branch name>      Prints the automatic deployment parameters for a branch
##   show-deploy-location           Prints the path to the directory where the repository files are deployed
##   version                        Prints the installed version
##   help                           Print this help

shopt -s nullglob

SOURCE_DIR=".gitserverlite"
source "$SOURCE_DIR/gsl-management-import"
source "$SOURCE_DIR/version"
source "$SOURCE_DIR/env"

DEPLOY_BRANCHES_DIR="$SOURCE_DIR/deploy_branches"
BRANCHES=("$DEPLOY_BRANCHES_DIR"/*)

COMMAND=$1
ARGUMENT1=$2

if [[ -z "$COMMAND" ]];
then
    invalid "command required."
fi

if [[ "$COMMAND" = "help" ]];
then
    display_manual
elif [ "$COMMAND" = "add-branch" ];
then
    add_branch $ARGUMENT1
elif [ "$COMMAND" = "remove-branch" ];
then
    remove_branch $ARGUMENT1
elif [ "$COMMAND" = "list" ];
then
    list "$BRANCHES" "$DEPLOY_BRANCHES_DIR"
elif [ "$COMMAND" = "show-branch" ];
then
    show_branch $ARGUMENT1
elif [ "$COMMAND" = "show-deploy-location" ];
then
    show_deploy_directory
elif [ "$COMMAND" = "version" ];
then
    show_version
else
    invalid "unknown command \"$COMMAND\"."
fi
