#!/usr/bin/env bash

#
# Copyright 2023 Task Re-engineering Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

#for debugging
#set -ex

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/gsl-eval"

branch() {
    local branch_location="$1"

    if [[ -z "$branch_location" ]];
    then
        exit 1
    fi

    local raw_branch="${branch_location#$GSL_DEPLOY_BRANCHES_DIR}"

    if [[ $raw_branch == /* ]];
    then
        echo "${raw_branch:1}"
    else
        echo "$raw_branch"
    fi
}

match() {
    local ref="$1"

    local match=""

    for branch_location in "${GSL_BRANCHES[@]}"
    do
        local branch="$(branch $branch_location)"

        if [[ "$ref" = "refs/heads/$branch" ]];
        then
            match="$branch_location"
        fi
    done

    echo "$match"
}

validate_branch_name() {
    local branch_name="$1"

    if [[ "$branch_name" =~ [^a-zA-Z0-9] ]];
    then
        exit 64
    fi
}
