#!/usr/bin/env bash

#
# Copyright 2023 Task Re-engineering Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

#for debugging
#set -ex

print_invalid_command() {
    echo -e "Invalid: invalid command.\n"
    display_manual
}

handle_exit() {
    local exit_status="$1"

    if [[ $exit_status -ne 0 ]];
    then
        if [[ $exit_status -eq 64 ]];
        then
            echo "Error: branch name must be alphanumeric."
        elif [[ $exit_status -eq 65 ]];
        then
            echo "Error: branch not found."
        else
            print_invalid_command
        fi
    fi
}
