#!/bin/bash

#for debugging
#set -ex

#
# Copyright © 2023 Task Re-engineering Inc.
# All rights reserved.
# 
# This source code is licensed under the [] license found in the
# LICENSE file in the root directory of this source tree. 
#

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/gsl-eval"
source "$SCRIPT_DIR/gsl-branch"

print_invalid_command() {
    echo -e "Invalid: invalid command.\n"
    display_manual
}

display_manual() {
    [ "$*" ] && echo "$0: $*"
    sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
}

add_branch() {
    BRANCH_NAME="$1"

    if [[ -z "$BRANCH_NAME" ]];
    then
        exit 1
    fi

    validate_branch_name "$BRANCH_NAME"
    
    echo "Enter the .env file name: (optional)"
    read -e ENV_FILE

    _create_branch_file "$BRANCH_NAME" "$ENV_FILE"

    echo "Deploy record for branch \"$BRANCH_NAME\" successfully created."
}

remove_branch() {
    BRANCH_NAME="$1"

    if [[ -z "$BRANCH_NAME" ]];
    then
        exit 1
    fi

    FILE="$DEPLOY_BRANCHES_DIR/$BRANCH_NAME"

    if [[ ! -f "$FILE" ]];
    then
        exit 1
    fi

    _remove_branch_file "$FILE"
    echo "Deploy record for branch $BRANCH_NAME successfully removed."
}

list() {
    BRANCHES="$1"
    DEPLOY_BRANCHES_DIR="$2"

    if [[ ${#BRANCHES[@]} == 0 ]];
    then
        echo "There are no deploy branch records configured."
    fi

    for BRANCH_LOCATION in "${BRANCHES[@]}"
    do
        echo "$(branch "$BRANCH_LOCATION" "$DEPLOY_BRANCHES_DIR")"
    done
}

show_branch() {
    local branch_name="$1"

    if [[ -z "$branch_name" ]];
    then
        exit 1
    fi

    local branch_location="$DEPLOY_BRANCHES_DIR/$branch_name"

    if [[ ! -f "$branch_location" ]];
    then
        exit 1
    fi

    echo -e "Displaying record for deploy branch $branch_name:"
    echo "==== START ===="
    cat "$branch_location"
    echo -e "===== END =====\n"
}

show_deploy_directory() {
    echo "$DEPLOY_DIR/"
}

show_version() {
    echo "gitserverlite version $VERSION"
}

run_selection() {
    command="$1"
    argument1="$2"

    if [[ -z "$command" ]];
    then
        exit 1
    fi

    if [[ "$command" = "help" ]];
    then
        display_manual
    elif [ "$command" = "add-branch" ];
    then
        add_branch $argument1
    elif [ "$command" = "remove-branch" ];
    then
        remove_branch $argument1
    elif [ "$command" = "list" ];
    then
        list "$BRANCHES" "$DEPLOY_BRANCHES_DIR"
    elif [ "$command" = "show-branch" ];
    then
        show_branch $argument1
    elif [ "$command" = "show-deploy-location" ];
    then
        show_deploy_directory
    elif [ "$command" = "version" ];
    then
        show_version
    else
        exit 1
    fi
}

_remove_branch_file() {
    BRANCH_NAME="$1"

    rm "$FILE"
}

_create_branch_file() {
    BRANCH_NAME="$1"
    ENV_FILE="$2"

    FILE="$DEPLOY_BRANCHES_DIR/$BRANCH_NAME"

    echo -e "# Deploy branch record for branch \"$BRANCH_NAME\"" > "$FILE"
    
    if [[ ! -z "$ENV_FILE" ]];
    then
        echo "ENV_FILE=$ENV_FILE" >> "$FILE"
    fi
}
