#!/bin/bash

#for debugging
#set -ex

#
# Copyright © 2023 Task Re-engineering Inc.
# All rights reserved.
# 
# This source code is licensed under the [] license found in the
# LICENSE file in the root directory of this source tree. 
#

shopt -s nullglob

get_branches() {
    GSL_BRANCHES=("$GSL_DEPLOY_BRANCHES_DIR"/*)
}

create_branch_file() {
    local branch_name="$1"
    local env_file="$2"

    local file="$GSL_DEPLOY_BRANCHES_DIR/$branch_name"

    echo -e "# Deploy branch record for branch \"$branch_name\"" > "$file"
    
    if [[ ! -z "$env_file" ]];
    then
        echo "env_file=$env_file" >> "$file"
    else
        echo -e "# No env-file specified. \".env\" will be used if it exists, otherwise none will be used." >> "$file"
    fi

    echo "Deploy record for branch \"$branch_name\" successfully created."
}

remove_branch_file() {
    local file="$1"

    if [[ ! -f "$file" ]];
    then
        exit 65
    fi

    rm -f "$file"

    echo "Deploy record for branch $branch_name successfully removed."
}

load_branch_file() {
    local branch_location="$1"

    source "$branch_location"
}
