#!/bin/bash

#
# Copyright 2023 Task Re-engineering Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

#for debugging
#set -ex

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/gsl-eval"
source "$SCRIPT_DIR/gsl-git"

process() {
    local git_dir="$1"
    local deploy_dir="$2"
    local params="$3"
    local branch="$4"
    local env_file="$5"

    if [[ -z "$git_dir" || -z "$deploy_dir" || -z "$params" || -z "$branch" ]];
    then
        exit 1
    fi
    
    local target="$deploy_dir/deploy_$branch"
    local run_command="checkout "$git_dir" "$branch" "$target"; deploy "$target" \""$params"\" "$env_file""
    _run "$run_command"
}

deploy() {
    local target="$1"
    local params="$2"
    local env_file="$3"

    if [[ -z "$target" || -z "$params" ]];
    then
        exit 1
    fi

    local run_command
    if [[ -z "$env_file" ]];
    then
        echo "Running Docker compose up. No environment file specified, so .env will be used if it exists."
        run_command="cd "$target"; docker compose up $params"
    else
        echo "Running Docker compose up with environment file \""$env_file"\"."
        run_command="cd "$target"; docker compose --env-file "$env_file" up $params"
    fi
    
    _run "$run_command"
}
