#!/bin/bash

#for debugging
#set -ex

#
# Copyright © 2023 Task Re-engineering Inc.
# All rights reserved.
# 
# This source code is licensed under the [] license found in the
# LICENSE file in the root directory of this source tree. 
#

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/gsl-eval"

branch() {
    local branch_location="$1"

    if [[ -z "$branch_location" ]];
    then
        exit 1
    fi

    local raw_branch="${branch_location#$GSL_DEPLOY_BRANCHES_DIR}"

    if [[ $raw_branch == /* ]];
    then
        echo "${raw_branch:1}"
    else
        echo "$raw_branch"
    fi
}

match() {
    local ref="$1"

    local match=""

    for branch_location in "${GSL_BRANCHES[@]}"
    do
        local branch="$(branch $branch_location)"

        if [[ "$ref" = "refs/heads/$branch" ]];
        then
            match="$branch_location"
        fi
    done

    echo "$match"
}

validate_branch_name() {
    local branch_name="$1"

    if [[ "$branch_name" =~ [^a-zA-Z0-9] ]];
    then
        exit 1
    fi
}
