#!/bin/bash

#for debugging
#set -ex

#
# Copyright © 2023 Task Re-engineering Inc.
# All rights reserved.
# 
# This source code is licensed under the [] license found in the
# LICENSE file in the root directory of this source tree. 
#

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/gsl-eval"
source "$SCRIPT_DIR/gsl-git"

process() {
        GIT_DIR="$1"
        DEPLOY_DIR="$2"
        PARAMS="$3"
        BRANCH="$4"
        ENV_FILE="$5"

        if [[ -z "$GIT_DIR" || -z "$DEPLOY_DIR" || -z "$PARAMS" || -z "$BRANCH" ]];
        then
                exit 1
        fi
        
        TARGET="$DEPLOY_DIR/deploy_$BRANCH"
        local PROCESS_CMD="checkout "$GIT_DIR" "$BRANCH" "$TARGET"; deploy "$TARGET" \""$PARAMS"\" "$ENV_FILE""

        local RESULT="$(_run "$PROCESS_CMD")"
        echo "$RESULT"
}

deploy() {
        TARGET="$1"
        PARAMS="$2"
        ENV_FILE="$3"

        if [[ -z "$TARGET" || -z "$PARAMS" ]];
        then
                exit 1
        fi

        local DEPLOY_CMD
        if [[ -z "$ENV_FILE" ]];
        then
                DEPLOY_CMD="cd "$TARGET"; docker compose up $PARAMS"
        else
                DEPLOY_CMD="cd "$TARGET"; docker compose --env-file "$ENV_FILE" up $PARAMS"
        fi
        
        local RESULT="$(_run "$DEPLOY_CMD")"
        echo "$RESULT"
}
