#!/bin/bash

#
# Copyright 2023 Task Re-engineering Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

#for debugging
#set -ex

get_branches() {
    GSL_BRANCHES=("$GSL_DEPLOY_BRANCHES_DIR"/*)
}

create_branch_file() {
    local branch_name="$1"
    local env_file="$2"

    local file="$GSL_DEPLOY_BRANCHES_DIR/$branch_name"

    echo -e "# Deploy branch record for branch \"$branch_name\"" > "$file"
    
    if [[ ! -z "$env_file" ]];
    then
        echo "env_file=$env_file" >> "$file"
    else
        echo -e "# No env-file specified. \".env\" will be used if it exists, otherwise none will be used." >> "$file"
    fi

    echo "Deploy record for branch \"$branch_name\" successfully created."
}

remove_branch_file() {
    local file="$1"

    if [[ ! -f "$file" ]];
    then
        exit 65
    fi

    rm -f "$file"

    echo "Deploy record for branch $branch_name successfully removed."
}

load_branch_file() {
    local branch_location="$1"

    source "$branch_location"
}
