#!/bin/bash

#for debugging
#set -ex

#
# Copyright © 2023 Task Re-engineering Inc.
# All rights reserved.
# 
# This source code is licensed under the [] license found in the
# LICENSE file in the root directory of this source tree. 
#

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/gsl-eval"

branch() {
        branch_location="$1"
        deploy_branches_dir="$2"
        
        if [[ -z "$branch_location" ]];
        then
                exit 1
        fi
        
        local raw_branch="${branch_location#$deploy_branches_dir}"
        
        if [[ $raw_branch == /* ]];
        then
                echo "${raw_branch:1}"
        else
                echo "$raw_branch"
        fi
}

validate_branch_name() {
    branch_name="$1"

    if [[ "$branch_name" =~ [^a-zA-Z0-9] ]];
    then
        exit 1
    fi
}
