#!/usr/bin/env bash

#
# Copyright 2023 Task Re-engineering Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

#for debugging
#set -ex

shopt -s nullglob

ref="$1"
GIT_DIR="$2"

GSL_DIR=".gitserverlite"

source "$GSL_DIR/env"
source "$GSL_DIR/gsl-branch"
source "$GSL_DIR/gsl-file"
source "$GSL_DIR/gsl-deploy"

GSL_DEPLOY_BRANCHES_DIR="$GSL_DIR/deploy_branches"
get_branches

match="$(match "$ref")"
if [[ ! -z "$match" ]];
then
    echo "Ref $ref received. Matches branch configured to automatically deploy."

    load_branch_file "$match"
    branch="$(branch "$match")"
    
    process "$GIT_DIR" "$GSL_DEPLOY_DIR" "$GSL_DOCKER_COMPOSE_UP_PARAMS" "$branch" "$env_file"
else
    echo "Ref $ref received. Doing nothing: does not match branches configured to automatically deploy."
fi
