#!/usr/bin/env bash

#
# Copyright 2023 Task Re-engineering Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

# 
# GitServerLite - A lightweight set of scripts to set up and manage a Git repository
#                 that automatically deploys your Dockerized services for you.
#                 https://github.com/TaskRe-engineering/GitServerLite
# 
# File: post-receive
# Author: Kier von Konigslow
# Created: February 5, 2023
# 
# This script is called by Git after references are updated on push.
# 

#for debugging
#set -ex

git_dir=$(pwd)

while read oldrev newrev ref
do
    if [[ -f "$git_dir/hooks/pre-deploy" ]];
    then
        "$git_dir/hooks/pre-deploy"
    fi

    "$git_dir/.gitserverlite/matchanddeploy" "$ref" "$git_dir"

    if [[ -f "$git_dir/hooks/post-deploy" ]];
    then
        "$git_dir/hooks/post-deploy"
    fi
done
